language: java
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk:
        - oraclejdk9
        - oraclejdk8
        - openjdk8
    - os: osx
      osx_image: xcode9.2
before_install:
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    linux)
      ;;
    osx)
      brew update
      brew install ant
      ;;
    esac;
