version: '{build}'
branches:
  only:
    - mirror
image: Visual Studio 2017
install:
  - cinst ant
  - refreshenv
build_script:
  - ant compile javadoc dist distmac distwin checkstyle pmd
test_script:
  - ant test
